//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaskumarNagganoNaZametku.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class zametki
    {
        public int id_zametki { get; set; }
        public string opisanie { get; set; }
        public Nullable<int> kategoria { get; set; }
        public string teg { get; set; }
    
        public virtual kategorii kategorii { get; set; }
    }
}
